### ISSUE TITLE
Cannot use non-const functors for sort

### ISSUE THREAD

**Issue by dinghram** [mattreecebentley/plf_list#10]
With std::list, I can use a functor with a non-const operator() when sorting. This can be helpful when the compare has to build some temporary data per item (like a display name), caching the value internally so that it doesn't have to build the display name every time that record is compared during the sort.

This can be fixed by adding a second, non-const operator() in sort_dereferencer with the same code as the const version. I am not sure this works on all compilers/platforms.

**Comment by mattreecebentley** [comment]
Good point - fixed.

**Comment by dinghram** [comment]
Thanks
