### ISSUE TITLE
License: Rename / Duplicate?

### ISSUE THREAD

**Issue by TPS** [mattreecebentley/plf_list#12]
@mattreecebentley Per https://help.github.com/articles/adding-a-license-to-a-repository/ , ifF you rename or duplicate (or perhaps quicker, commit directly from https://choosealicense.com/licenses/zlib/ ) your current license file to LICENSE or LICENSE.md, GitHub interface will pick it up, & show your repo license type in the header & searches that restrict to open-source licenses.

**Comment by mattreecebentley** [comment]
I don't get it.
What's the advantage??

**Comment by TPS** [comment]
Mostly so those of us who use the GitHub repo & search interfaces will be able to find/use this more clearly.

**Comment by mattreecebentley** [comment]
Ah, I see - Thanks

**Comment by TPS** [comment]
Thanks for taking the RFE seriously via https://github.com/mattreecebentley/plf_list/commit/6c193db9ad2c63e0521eda07e4f296186b3ec2d6 🙇

**Comment by mattreecebentley** [comment]
You are most welcome.
