### ISSUE TITLE
Compiler warnings "type qualifiers ignored on cast result type"

### ISSUE THREAD

**Issue by glebov-andrey** [mattreecebentley/plf_list#13]
Every usage of the macro
```
#define PLF_LIST_BLOCK_MIN static_cast<const group_size_type>(...)
```
results in a warning with GCC because `const` does not do anything in the cast result type.
The specific warning is `-Wignored-qualifiers`.

Removing `const` should fix it.

**Comment by mattreecebentley** [comment]
Thanks for that - have fixed.
