### ISSUE TITLE
PLF_CPP20_SUPPORT bugs insert due to multiple reasons. On Visual Studio latest version

### ISSUE THREAD

**Issue by HSNB** [mattreecebentley/plf_list#18]
with PLF_CPP20_SUPPORT enabled these issues occur:

1. insert() returns void (should be iterator)
2. insert() gives me other vague errors about not being able to find matching parameters, probably due to the iterator parameters that I don't fill in my code as that's not normally required.

I have to comment out PLF_CPP20_SUPPORT to make it compile.

**Comment by mattreecebentley** [comment]
Okay will test these in a few days, can you send me the insert line in your code which is causing the issue?

**Comment by HSNB** [comment]
Hi,

After making an empty project to find the cause, I found the issues are actually happening solely due to using the shrink_to_fit() function in combination with *C++ Language Standard* compiler option set to "Preview - Features from the Latest C++ Working Draft (/std:c++latest)".

code:
```
plf::list<int> bug;
bug.shrink_to_fit();
```

The issue doesn't occur if that compiler option is set to "ISO C++17 Standard (/std:c++17)"

For that reason, I don't know if it's actually Visual Studio's fault since it's called a "Preview" option after all and maybe that is considered experimental?

**Comment by mattreecebentley** [comment]
Hi, 
'preview' just means the limited set of features they're supporting for the next version of C++ (20 in this case), not that the compiler is necessarily broken or anything.
However looking at the code I think this could be a bug in MSVC, however I won't be able to test for a few days. shrink_to_fit can call insert- but, it shouldn't be calling it on an empty list - is that the whole of your code?
Will be in touch-

**Comment by HSNB** [comment]
Whole code:

```
#include "plf_list.h"

int main()
{
	plf::list<int> bug;
	bug.shrink_to_fit();
}
```

Error:

> 1>------ Build started: Project: tryplflist, Configuration: Debug Win32 ------
> 1>tryplflist.cpp
> 1>F:\tryplflist\plf_list.h(2362,1): error C2678: binary '++': no operator found which takes a left-hand operand of type 'const iterator_type1' (or there is no acceptable conversion)
> 1>        with
> 1>        [
> 1>            iterator_type1=std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>
> 1>        ]
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\xutility(4050,33): message : could be 'std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>> &std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>::operator ++(void)'
> 1>F:\tryplflist\plf_list.h(2362,1): message : while trying to match the argument list '(const iterator_type1)'
> 1>        with
> 1>        [
> 1>            iterator_type1=std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>
> 1>        ]
> 1>F:\tryplflist\plf_list.h(2994): message : see reference to function template instantiation 'void plf::list<int,std::allocator<int>>::insert<std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>,std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>>(const plf::list<int,std::allocator<int>>::list_iterator<true>,const iterator_type1,const iterator_type2)' being compiled
> 1>        with
> 1>        [
> 1>            iterator_type1=std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>,
> 1>            iterator_type2=std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>
> 1>        ]
> 1>F:\tryplflist\plf_list.h(2994): message : see reference to function template instantiation 'void plf::list<int,std::allocator<int>>::insert<std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>,std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>>(const plf::list<int,std::allocator<int>>::list_iterator<true>,const iterator_type1,const iterator_type2)' being compiled
> 1>        with
> 1>        [
> 1>            iterator_type1=std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>,
> 1>            iterator_type2=std::move_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>
> 1>        ]
> 1>F:\tryplflist\plf_list.h(2971): message : while compiling class template member function 'void plf::list<int,std::allocator<int>>::shrink_to_fit(void)'
> 1>F:\tryplflist\tryplflist.cpp(7): message : see reference to function template instantiation 'void plf::list<int,std::allocator<int>>::shrink_to_fit(void)' being compiled
> 1>F:\tryplflist\tryplflist.cpp(6): message : see reference to class template instantiation 'plf::list<int,std::allocator<int>>' being compiled
> 1>F:\tryplflist\plf_list.h(2357,4): error C2562: 'plf::list<int,std::allocator<int>>::insert': 'void' function returning a value
> 1>F:\tryplflist\plf_list.h(2345): message : see declaration of 'plf::list<int,std::allocator<int>>::insert'
> 1>F:\tryplflist\plf_list.h(2367,3): error C2562: 'plf::list<int,std::allocator<int>>::insert': 'void' function returning a value
> 1>F:\tryplflist\plf_list.h(2345): message : see declaration of 'plf::list<int,std::allocator<int>>::insert'
> 1>Done building project "tryplflist.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Visual Studio Community 2019 - Version 16.9.6
Only with compiler flag "Preview - Features from the Latest C++ Working Draft (/std:c++latest)"

Btw the download links for your library links are broken for pretty much all of them on your website plflib.org. Don't know where else to tell you ^^' Maybe link it to your github repos so you don't have to update them manually.

**Comment by mattreecebentley** [comment]
I believe this is fixed now, but double-check just to make certain.
Thanks for the headsup on website.
