### ISSUE TITLE
Move assignment of empty list in gcc 5/6 results in a segfault

### ISSUE THREAD

**Issue by cscrimge** [mattreecebentley/plf_list#2]
When building with gcc 5.4.1 and gcc 6.3.0 on Ubuntu 16.04 with --std=c++11 or c++14, assigning one empty `plf::list` to another results in a segfault.

There is no issue in gcc 7.2.

My repro test case:
```C++
#include "plf_list.h"

int main(int argc, char* argv[])
{
   plf::list<int> testList;

   testList = plf::list<int>();
}
```

**Comment by mattreecebentley** [comment]
Thanks, fixed in most recent version, just now.  Same thing happened on move-construction, so, glad you pointed it out.
