### ISSUE TITLE
ranges reverse_view and such no longer work and give compile error

### ISSUE THREAD

**Issue by HSNB** [mattreecebentley/plf_list#25]
plf::list used to support for loop with reverse ranges, but now no longer compiles

```
plf::list<int> abc;
for (int x : std::ranges::reverse_view(abc)) {
}
for (int x : abc | std::views::reverse) {
}
for (int x : std::views::reverse(abc)) {
}
```

All of these give compile errors:

> ranges(4854,36): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'std::reverse_iterator<plf::list<int,std::allocator<int>>::list_iterator<false>>'
> message : No constructor could take the source type, or constructor overload resolution was ambiguous

On MSVC 2022

**Comment by HSNB** [comment]
Workaround:

```
plf::list<int> abc;
for (int x : std::ranges::reverse_view(std::ranges::take_view(abc, abc.size()))) {
}
```

**Comment by mattreecebentley** [comment]
Fixed as of last couple of updates - thanks

**Comment by HSNB** [comment]
it crashes now
