### ISSUE TITLE
ranges reverse_view and such cause crash

### ISSUE THREAD

**Issue by HSNB** [mattreecebentley/plf_list#26]
see [issue](https://github.com/mattreecebentley/plf_list/issues/25)

**Comment by mattreecebentley** [comment]
You're going to have to supply some crashing code, because the code you supplied for the previous issue does not crash, at least on my setup.

**Comment by HSNB** [comment]
Hi,

It doesn't necessarily crash. The first element in the reverse_view loop references the end iterator which may or may not point to invalid memory. If the list contains an ints, it doesn't crash but will just print garbage. If it contains something like a smart pointers it almost certainly will.

```
plf::list<int> abc;
abc.push_back(4);
abc.push_back(5);
abc.push_back(6);
abc.push_back(7);
for (int x : std::ranges::reverse_view(abc)) {
  std::cout << x << std::endl;
}
```

Printed numbers: 348271231, 7, 6, 5

**Comment by mattreecebentley** [comment]
Fixed.
