### ISSUE TITLE
No `begin()` and `rbegin()` for `const-` qualified lists

### ISSUE THREAD

**Issue by ed94a9** [mattreecebentley/plf_list#27]
I am trying replace `std::list` with `plf::list` in my codebase for test. Problem occurs as there are no overloads with `const_iterator plf::list::begin () const PLF_NOEXCEPT` and `const_reverse_iterator plf::list::rbegin() const PLF_NOEXCEPT`. Those exist STL: [cppreference](https://en.cppreference.com/w/cpp/container/list/rbegin)

**Comment by mattreecebentley** [comment]
No, those functions exist. Check the github code.
