### ISSUE TITLE
Iterators could be trivially copyable

### ISSUE THREAD

**Issue by glebov-andrey** [mattreecebentley/plf_list#33]
Hi,

I was just trying to type-erase `plf::list<T>::iterator`s by `std::bit_cast`ing to/from `void *` (for compile-time performance optimization reasons), and came across the fact the they aren't trivially copyable.
I assume the copy/move ctor/assign-ops are not defaulted because of C++98 support, but they could definitely be defaulted in C++11 and later.
While patching them, I came across a few other oddities with iterators:
- some move constructors and assignment operators take a `const` rvalue reference, which makes them act like copies
- the default constructors could be `constexpr` in C++11 and later
- initializing `node_pointer` with the `NULL` macro might not work for all fancy pointer types (as far as I can tell, only value-initialization and conversion from `std::nullptr_t` are required)
- `list_reverse_iterator` has duplicate move constructor definitions with differing parameter `const`-ness
- _(not in my patch)_ this constructor's parameter type doesn't match its counterpart in the first `#ifdef` branch: https://github.com/mattreecebentley/plf_list/blob/de5e4f9a1f97d2a5bed34d792ff03564b6d88eee/plf_list.h#L3726

Here's my patch (it would need some changes for C++98 support):
```patch
diff --git a/plf_list.h b/plf_list.h
index 192e106..5e11c1c 100644
--- a/plf_list.h
+++ b/plf_list.h
@@ -3548,11 +3548,7 @@ public:
 
 
 
-		list_iterator & operator = (const list_iterator &rh) PLF_NOEXCEPT
-		{
-			node_pointer = rh.node_pointer;
-			return *this;
-		}
+		list_iterator & operator = (const list_iterator &rh) PLF_NOEXCEPT = default;
 
 
 
@@ -3570,19 +3566,14 @@ public:
 
 
 		#ifdef PLF_MOVE_SEMANTICS_SUPPORT
-			list_iterator & operator = (const list_iterator &&rh) PLF_NOEXCEPT
-			{
-				assert (&rh != this);
-				node_pointer = std::move(rh.node_pointer);
-				return *this;
-			}
+			list_iterator & operator = (list_iterator &&rh) PLF_NOEXCEPT = default;
 
 
 			#ifdef PLF_DEFAULT_TEMPLATE_ARGUMENT_SUPPORT
 				template <bool is_const_it = is_const, class = typename plf::enable_if<is_const_it>::type >
-				list_iterator & operator = (const list_iterator<false> &&rh) PLF_NOEXCEPT
+				list_iterator & operator = (list_iterator<false> &&rh) PLF_NOEXCEPT
 			#else
-				list_iterator & operator = (const list_iterator<!is_const> &&rh) PLF_NOEXCEPT
+				list_iterator & operator = (list_iterator<!is_const> &&rh) PLF_NOEXCEPT
 			#endif
 			{
 				node_pointer = std::move(rh.node_pointer);
@@ -3592,9 +3583,9 @@ public:
 
 
 
-		list_iterator() PLF_NOEXCEPT: node_pointer(NULL) {}
+		constexpr list_iterator() PLF_NOEXCEPT: node_pointer() {}
 
-		list_iterator(const list_iterator &source) PLF_NOEXCEPT: node_pointer(source.node_pointer) {}
+		list_iterator(const list_iterator &source) PLF_NOEXCEPT = default;
 
 
 		#ifdef PLF_DEFAULT_TEMPLATE_ARGUMENT_SUPPORT
@@ -3606,13 +3597,13 @@ public:
 
 
 		#ifdef PLF_MOVE_SEMANTICS_SUPPORT
-			list_iterator (const list_iterator &&source) PLF_NOEXCEPT: node_pointer(std::move(source.node_pointer)) {}
+			list_iterator (list_iterator &&source) PLF_NOEXCEPT = default;
 
 			#ifdef PLF_DEFAULT_TEMPLATE_ARGUMENT_SUPPORT
 				template <bool is_const_it = is_const, class = typename plf::enable_if<is_const_it>::type >
-				list_iterator(const list_iterator<false> &&source) PLF_NOEXCEPT: node_pointer(std::move(source.node_pointer)) {}
+				list_iterator(list_iterator<false> &&source) PLF_NOEXCEPT: node_pointer(std::move(source.node_pointer)) {}
 			#else
-				list_iterator(const list_iterator<!is_const> &&source) PLF_NOEXCEPT: node_pointer(std::move(source.node_pointer)) {}
+				list_iterator(list_iterator<!is_const> &&source) PLF_NOEXCEPT: node_pointer(std::move(source.node_pointer)) {}
 			#endif
 		#endif
 
@@ -3726,17 +3717,10 @@ public:
 
 
 
-		list_reverse_iterator() PLF_NOEXCEPT: node_pointer(NULL) {}
-
+		constexpr list_reverse_iterator() PLF_NOEXCEPT: node_pointer() {}
 
-		list_reverse_iterator(const list_reverse_iterator &source) PLF_NOEXCEPT: node_pointer(source.node_pointer) {}
-
-
-		#ifdef PLF_MOVE_SEMANTICS_SUPPORT
-			list_reverse_iterator (const list_reverse_iterator &&source) PLF_NOEXCEPT: node_pointer(std::move(source.node_pointer)) {}
 
-			list_reverse_iterator (const list_reverse_iterator<!is_const_r> &&source) PLF_NOEXCEPT: node_pointer(std::move(source.node_pointer)) {}
-		#endif
+		list_reverse_iterator(const list_reverse_iterator &source) PLF_NOEXCEPT = default;
 
 
 		#ifdef PLF_DEFAULT_TEMPLATE_ARGUMENT_SUPPORT
@@ -3765,16 +3749,14 @@ public:
 
 
 		#ifdef PLF_MOVE_SEMANTICS_SUPPORT
-			list_reverse_iterator (list_reverse_iterator &&source) PLF_NOEXCEPT:
-				node_pointer(std::move(source.node_pointer))
-			{}
+			list_reverse_iterator (list_reverse_iterator &&source) PLF_NOEXCEPT = default;
 
 
 			#ifdef PLF_DEFAULT_TEMPLATE_ARGUMENT_SUPPORT
 				template <bool is_const_rit = is_const_r, class = typename plf::enable_if<is_const_rit>::type >
 				list_reverse_iterator (list_reverse_iterator<false> &&source) PLF_NOEXCEPT:
 			#else
-				list_reverse_iterator (const list_iterator<!is_const_r> &&source) PLF_NOEXCEPT:
+				list_reverse_iterator (list_iterator<!is_const_r> &&source) PLF_NOEXCEPT:
 			#endif
 				node_pointer(std::move(source.node_pointer))
 			{}
@@ -3800,11 +3782,7 @@ public:
 		}
 
 
-		list_reverse_iterator& operator = (const list_reverse_iterator &source) PLF_NOEXCEPT
-		{
-			node_pointer = source.node_pointer;
-			return *this;
-		}
+		list_reverse_iterator& operator = (const list_reverse_iterator &source) PLF_NOEXCEPT = default;
 
 
 		#ifdef PLF_DEFAULT_TEMPLATE_ARGUMENT_SUPPORT
@@ -3820,12 +3798,7 @@ public:
 
 
 		#ifdef PLF_MOVE_SEMANTICS_SUPPORT
-			list_reverse_iterator& operator = (list_reverse_iterator &&source) PLF_NOEXCEPT
-			{
-				assert (&source != this);
-				node_pointer = std::move(source.node_pointer);
-				return *this;
-			}
+			list_reverse_iterator& operator = (list_reverse_iterator &&source) PLF_NOEXCEPT = default;
 
 
 			#ifdef PLF_DEFAULT_TEMPLATE_ARGUMENT_SUPPORT
```

**Comment by mattreecebentley** [comment]
Just caught this. The const move operations should definitely be fixed, but the defaulting means it's inoperable in C++98/03.
I'll look at it, if it messes with benchmarks I'll stick with non-defaults (this is what happened for colony - defaulting made some benchmarks slower), otherwise it might be possible, just annoying, to make them default.
NULL is just a macro for 0, so should be fine.

**Comment by mattreecebentley** [comment]
Have updated with the incorrectness fixes - thanks for that - as for the rest,
I'm think I'll leave this for the moment, since the templated constructors can't be defaulted, and benchmarking shows no performance difference between the default'd and non-default'd constructors/assignments. If you see a particular reason why defaulting some of the constructors would be worthwhile, let me know. Also, why do you think constexpr'ing the default constructor would be useful? Since the container as a whole isn't constexpr.
Cheers-

**Comment by glebov-andrey** [comment]
Thanks for taking a look!

> defaulting made some benchmarks slower

Hmm, well that's counter-intuitive!

> NULL is just a macro for 0, so should be fine.

Oh, interesting - I didn't know that `std::nullptr_t` is implicitly constructible from literal `0`.

Regarding the `constexpr` default-constructor and trivial copy/move constructors, my particular case is rather exotic (roughly):
```c++
using list_iter_t = plf::list<CacheEntry>::iterator;
enum class cache_entry_t : std::uintptr_t {} // for use in interfaces without including <plf_list.h> and instantiating plf::list
static_assert(std::bit_cast<cache_entry_t>(list_iter_t{}) == cache_entry_t{}); // this is where the constexpr default constructor is used

// somewhere in the implementation:
return std::bit_cast<cache_entry_t>(iter); // std::bit_cast requires types to be trivially copyable
auto iter = std::bit_cast<list_iter_t>(entry);
```

For the `constexpr` default constructor I can imagine cases where the initial value of an iterator should be initialized at compile time, e.g.
```c++
thread_local constinit plf::list<Entry>::iterator current_thread_entry{};
```

As for triviality, it's more of a potential for `memcpy`-like optimizations to kick in, including for compound types which include these iterators.

These are of course all rather niche cases, so feel free to close this - I'll just keep a patch for the above use case.

**Comment by mattreecebentley** [comment]
Yes, it's very strange re: worse performance for defaulting, but it only happens for colony. For list, I could do it, but I would have to re-write the iterators in terms of inheritance for const/non-const rather than the template-based way I've currently got it. Reason being is the templated constructors are necessary to prevent const-to-non-const assignment/construction of iterators. Happy to add constexpr on the default constructor though.

**Comment by glebov-andrey** [comment]
Regarding the templated constructor/operator overloads: these don't hinder triviality, as long as they are constrained enough, because they aren't considered for the [trivially copyable class](https://en.cppreference.com/w/cpp/language/classes#Trivially_copyable_class) requirements. In fact the code from my example works with the patch I provided initially.
