### ISSUE TITLE
Compile warning

### ISSUE THREAD

**Issue by dinghram** [mattreecebentley/plf_list#9]
On Visual Studio 2017, I get the warning:
warning C4458: declaration of 'end_node' hides class member

on this line:
inline PLF_LIST_FORCE_INLINE void destroy_all_node_pointers(group_pointer_type const group_to_process, const node_pointer_type end_node) PLF_LIST_NOEXCEPT

If you rename end_node parameter, this warning goes away.

**Comment by mattreecebentley** [comment]
Out of interest which warning level did you have turned on to see this warning? 

Fixed at any rate.

**Comment by dinghram** [comment]
Level 4 (/W4)
